- slash/loader.py
simple change that allow to declare the order of tests in a directory.
before
```
slash run test_dir/
10 tests collected   
test_dir/a_00.py .  PASS
test_dir/a_04.py .  PASS
test_dir/a_06.py .  PASS
test_dir/a_01.py .  PASS
test_dir/a_07.py .  PASS
test_dir/a_08.py .  PASS
test_dir/a_03.py .  PASS
test_dir/a_02.py .  PASS
test_dir/a_09.py .  PASS
test_dir/a_05.py .  PASS
```
after
```
slash run test_dir/
10 tests collected   
test_dir/a_00.py .  PASS
test_dir/a_01.py .  PASS
test_dir/a_02.py .  PASS
test_dir/a_03.py .  PASS
test_dir/a_04.py .  PASS
test_dir/a_05.py .  PASS
test_dir/a_06.py .  PASS
test_dir/a_07.py .  PASS
test_dir/a_08.py .  PASS
test_dir/a_09.py .  PASS
```
> sort test files in directory

- slash/plugins/builtin/xunit.py
Hi,
When getting an error outside the test (like import error), using xunit plugin add another error of "Failed to add error to result" which hide the real error.
The PR is suggestion of work-around about the issue
Thanks,
Eli
> [xunit-plugin] fix "Failed to add error to result" error

- slash/log.py
logging cause a exception int/bool/None like:
```
Traceback (most recent call last):
File "/local/lib/python2.7/site-packages/logbook/handlers.py", line 212, in handle
self.emit(record)
File "/local/lib/python2.7/site-packages/slash/log.py", line 97, in emit
returned = super(ConsoleHandler, self).emit(record)
File "/local/lib/python2.7/site-packages/logbook/handlers.py", line 579, in emit
msg = self.format(record)
File "/local/lib/python2.7/site-packages/slash/log.py", line 81, in format
if self._truncate_lines and len(orig_message) > self.MAX_LINE_LENGTH and should_truncate:
TypeError: object of type 'int' has no len()
Logged from file test_a.py, line 29
```
> log: fix non-string logs emitting

- doc/advanced_usage.rst
Must load tests for their hooks to be registered, which is used by get_started_context to call the session start and end hooks.
> Fix documentation for slash.run_tests.

- slash/runner.py
- tests/test_running.py
@vmalloc As we discussed a long time ago (sorry for the late PR), sometimes we run with `--pdb` flag but due to multiple errors we want to stop entering debugger.
This PR should fix it by removing the caching of `config.root.run.stop_on_error`.
> Support changing stop_on_error configuration during session

- slash/loader.py
When using a test path like ```c:\path\to\my\test.py``` this was incorrectly detected as path="c" and address_in_file="\path\to\my\test.py"
> Fix issue with some windows file path

- slash/core/local_config.py
- slash/loader.py
On windows this was causing issue if the drive letter specified by the user was lower case.
> Normalize the case of a path when traversing upwards

- slash/parallel/server.py
Moving `server` initialization outside the try/except block removes the shadowing exception on the finally stage if server creation failed.
> move server init outside try/except

- requirements.txt
Python 6.0+ does not support Python 2.6, 2.7, 3.0, 3.1, or 3.2.
When using Python 2.7, please install IPython 5.x LTS Long Term Support version.
Beginning with IPython 6.0, Python 3.3 and above is required.
> Use IPython 5.x LTS for Python version before 3.3

- doc/changelog.rst
- doc/development.rst
- slash/frontend/main.py
**On Windows, calling init() will filter ANSI escape sequences out of any
text sent to stdout or stderr, and replace them with equivalent Win32
calls.**
From Colorama readme:
https://github.com/tartley/colorama#initialisation
> Applications should initialise Colorama using:
> 
> ```python
> from colorama import init
> init()
> ```
> 
> On Windows, calling init() will filter ANSI escape sequences out of any
> text sent to stdout or stderr, and replace them with equivalent Win32
> calls.
> 
> On other platforms, calling init() has no effect (unless you request
> other optional functionality; see “Init Keyword Args”, below). By
> design, this permits applications to call init() unconditionally on
> all platforms, after which ANSI output should just work.
> 
> To stop using colorama before …
> Adding colorama init and deinit (fix #668)

- doc/changelog.rst
- slash/loader.py
- tests/test_test_loading.py
On btrfs this assumption is wrong
> Tests loader assumes dirnames returned sorted from os.walk

- doc/slash_run.rst
- slash/utils/suite_files.py
- tests/test_suite_files.py
Also renamed `filter` to `matcher` to avoid shadowing python built it name.
This change allow to have a suite file that looks like:
```
tests\test_1.py  # repeat: 5
tests\test_2.py  # repeat: 3
tests\test_4.py
tests  # filter: id=3, repeat: 4
tests  # repeat: 2, filter: abc
```
> Allow "repeat: x" in suite file

- doc/changelog.rst
- slash/core/metadata.py
- slash/loader.py
- tests/test_repeat.py
Adding repeat_all_index in test metadata to help sorting tests correctly when using repeat-all.
With the current implementation, repeat-each and repeat-all is producing the same list of tests.
If you have 3 tests called a, b and c. With `--repeat-each 2` or `--repeat-all 2` the result will be:
```
a
a
b
b
c
c
```
_____________________
Now with this change, 
`--repeat-each 2` the result will be:
```
a
a
b
b
c
c
```
`--repeat-all 2` the result will be:
```
a
b
c
a
b
c
```
> Adding repeat_all_index in test metadata to help sorting

- slash/plugins/builtin/xunit.py
- tests/test_xunit_plugin.py
Currently the xnuit plugin do not supports result details that are not
directly xml serializable. This includes details that can be added
using slash.context.result.details.append (detail value becomes a list).
With this change, slash.context.result.details.append is fully
supported in addition with supports for other detail values like dict,
list and tuple.
> Adding support for details coming from result.details.append in xunit

- doc/fixtures.rst
The double colon was causing issue when rendering the sphinx documentation.
See the code block bellow https://slash.readthedocs.io/en/develop/fixtures.html#the-use-fixtures-decorator
> Removing double colon causing doc rendering issues

- slash/core/fixtures/fixture_store.py
- tests/test_fixture_start_end_test.py
Currently if there is an exception raised from one of the fixture test_start, the test before and other tests method are not called. In addition, this fixture test_start will not be called again until all the fixtures test_start have been called once without exceptions. This leads to funky results...
```python
import slash
@slash.fixture(scope='session')
def fixture1(this):
slash.logger.info("Hi from fixture 1")
@this.test_start
def at_test_start():
slash.logger.info("on test start fixture 1")
raise Exception("from fixture 1")
return 1
@slash.fixture(scope='session')
def fixture2(this):
slash.logger.info("Hi from fixture 2")
@this.test_start
def at_test_start():
slash.logger.info("on test start fixture 2")
raise AssertionError("from fixture 2")
return 2
class Sample(slash.Test):
def …
```
> Correctly call fixture test_start for each test

- tests/test_warning_ignored.py
On windows failing to escape the `\` is causing failure to compile the regular expressions
> Escaping special characters __file__ path

- doc/changelog.rst
- slash/core/fixtures/fixture_store.py
- slash/core/test.py
- tests/test_fixture_start_end_test.py
Restoring the behavior described in the **note** section here https://slash.readthedocs.io/en/master/fixtures.html#test-start-end-for-widely-scoped-fixtures
> Note: 
Exceptions propagating out of the test_start or test_end hooks will fail the test, possibly preventing it from starting properly
> Correctly propagating exceptions out of the test_start or test_end hooks

- doc/changelog.rst
- slash/core/fixtures/parameters.py
- slash/core/function_test.py
- slash/core/tagging.py
- slash/core/variation.py
- tests/test_test_parameters.py
- tests/utils/suite_builder.py
How about this?
Not sure which style is most appropriate:
```
@slash.parametrize('x', [
500 // slash.param(tags=["regression"]),
5 // slash.param(tags="sanity"),
])
@slash.parametrize('y', [
'100' // slash.tag("regression", "long"),
'10' // slash.tag("regression", "short"),
'1' // slash.tag("sanity"),
])
@slash.parametrize('z', [True, False])
def test_1(x, y, z):
print(x, y, z)
```
There's one issue though when using tags with different values on different parameter-values, which generates tag conflicts.
> Add support for tagging parameterization values

- setup.cfg
Releases package is currently broken with newest `semantic-version` package, which is one of its dependencies (see https://github.com/bitprophet/releases/issues/84).
In addition, it depends on Sphinx<1.8.
I pinned these 3 packages (in doc extras) until the issue will be fixed.
> Fix documentation pipeline

- doc/changelog.rst
- slash/utils/python.py
This will avoid decoding errors when files are in different encodings
> Read file as binary

- slash/utils/interactive.py
We use gevent's monkey patching which has 'read-only' version of these objects, and we fail:
```
Traceback (most recent call last):
*/slash/frontend/slash_run.py:64 ................ slash_run >> with app.session.get_started_context():                  
/usr/local/lib/python3.7/contextlib.py:112 ...... __enter__ >> return next(self.gen)                                    
*/slash/core/session.py:122 ........... get_started_context >> with notify_if_slow_context("Initializing session..."):  
/usr/local/lib/python3.7/contextlib.py:112 ...... __enter__ >> return next(self.gen)                                    
*/slash/utils/interactive.py:66 .... notify_if_slow_context >> evt.should_report_end_msg = False                        
AttributeError: 'gevent._event.Event' object has no attribute …
```
> don't set attributes on threading.Event objects

- slash/loader.py
- slash/resuming.py
- tests/test_slash_resume.py
The slash fails to collect the class based test on rerun or resume. when saving test for resume it saves only the function name. While collecting test it compares with the address in file.
```
def _iter_test_resume(self, resume_state):
for test in self._iter_path(resume_state.file_name):
if resume_state.function_name == test.__slash__.address_in_file:
if resume_state.variation:
if not resume_state.variation == test.get_variation().id:
continue
yield test
```
Instead of function name saved the address in file property in ResumeState(function_name = address_in_file)
#948 
```
slash resume random-previous session-id
```
> Fix for bug #948

- doc/changelog.rst
- slash/plugins/builtin/xunit.py
- tests/test_xunit_plugin.py
This changeset adds conversion of float and integer test detail values to strings when writing xunit output, allowing tests which store float and integer test details to also generate xunit output.
> Convert float and integer test details to strings in xunit output files

- slash/utils/traceback_proxy.py
An attempt to use ipython's post-mortem code with `--pdb` failed deep inside, when ipython called on `inspect.getinnerframes`, which eventually failed on `inspect.getframeinfo`. The latter checks `if istraceback(frame)`, and falls into the wrong code path since `frame` is a TracebackProxy`
> make 'TracebackProxy' compatible with 'inspect', which checks for types.TracebackType

- setup.cfg
- tests/conftest.py
* Remove pytest-catchlog dependency (it was merged into pytest core and now emits warning)
* Add stderr logbook handler to unittests
> Unittests log tasks

- doc/changelog.rst
- slash/utils/suite_files.py
- tests/test_suite_files.py
Slash creates test path and test address based on how it is invoked. when the test path provided is relative then the test path and address of a test will be relative. 
```
slash list tests\test_script.py
``` 
If the path is provided as absolute then the test_path and address will be absolute.
```
slash list C:\package\tests\test_script.py
```
But when slash list or slash run is invoked with help of suite file the test path and test address of the test collected is always absolute irrespective of path provided in suite file.
modified the iter_suite_file_paths method to provide relative path when relative path is provided and absolute path when absolute path is provided in suite_file
> modified iter_suite_file_paths to get the test path as relative if the path is provided relative in the suite file

- doc/changelog.rst
- slash/core/test.py
- tests/test_tagging.py
- tests/test_test_parameters.py
The New feature from slash 1.9.0 lets the tester to add tag to the test params. This tagging of test param is not working for class based test. Unable to filter the tests that are tagged in params of class based tests.
Sample code
```
class SampleTest(slash.Test):
@slash.tag("settings")
@slash.parametrize(
"choose_door_keypad", ["new" // slash.param("T1", tags="bt-sanity"),
"existing" // slash.param("T2")])
def test_5(self, choose_door_keypad):
print("testing 5:" + choose_door_keypad)
``` 
In the above sample code tags are provided to param of class based test. when trying to filter the test with the tag. slash is unable to filter it.
```
slash run -k tag:bt-sanity <path-of-the-script>
```
fetched the tags of params while getting the tags in get_tags method in class Test
> Fix tag param for class test

- slash/plugins/builtin/xunit.py
- tests/test_xunit_plugin.py
The passed test and the not run test looks the same in the xunit XML report.  
When xunit xml reports are parsed through  [xunit](https://plugins.jenkins.io/xunit/) plugin in the jenkins. The Jenkins reports even the not run as passed tests. 
Following are the link which I referred for the Junit XML schema since the slash xunit report is similar to Junit xml report
- https://llg.cubic.org/docs/junit/
- https://github.com/windyroad/JUnit-Schema/blob/master/JUnit.xsd
- https://github.com/junit-team/junit5/blob/main/platform-tests/src/test/resources/jenkins-junit.xsd
- https://help.catchsoftware.com/display/ET/JUnit+Format
On the XML report Schema in the Junit xml report no where it is mentioned to report the not run test results in the report.
modified xunit report plugin to report only the …
> Modified xunit plugin not to report the not run tests

- setup.py
Recent changes to setuptools (https://github.com/pypa/setuptools/issues/3790) released in version 67.0.0 make the `python_requires` check more strick and **prevents the installation of Slash.**
> Make python_requires PEP 440 compatible

- doc/slash_run.rst
- slash/conf.py
- slash/resuming.py
- tests/test_slash_resume.py
Adding `unstarted-only-without-skipped` option when resuming.
> Add flag for resuming session without skipped tests

- slash/plugins/builtin/xunit.py
Empty string` classname` is causing issues in some parsers and here the `classname` is really `None` and not `""`
> Remove xunit testcase classname attribute for test functions

- slash/frontend/slash_list.py
Reporting fixtures that are one another drive is broken on Windows.
In `os.path.relpath` on Windows, `ValueError` is raised when path and start are on different drives.
> Reporting fixtures that are one another drive is broken on Windows
